site_name: DevOps
theme:
  language: en
  name: material
  logo: img/logo/logo.png
  favicon: img/logo/logo.png
  palette:
    primary: deep purple
    accent: deep purple
    scheme: slate
  feature:
    tabs: true
plugins:
  - search:
      lang: ["ru", "en"]
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra:
  generator: false
