site_name: DevOps
theme:
  language: en
  name: material
  logo: img/logo/logo.png
  favicon: img/logo/logo.png
  # palette:
    # primary: deep purple
    # accent: deep purple
  palette: 

    # Palette toggle for light mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  feature:
    tabs: true
plugins:
  - search:
      lang: ["ru", "en"]
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra:
  generator: false